[package]
name = "gfx-backend-gl"
version = "0.4.0"
description = "OpenGL backend for gfx-rs"
homepage = "https://github.com/gfx-rs/gfx"
repository = "https://github.com/gfx-rs/gfx"
keywords = ["graphics", "gamedev"]
license = "MIT OR Apache-2.0"
authors = ["The Gfx-rs Developers"]
readme = "README.md"
documentation = "https://docs.rs/gfx-backend-gl"
workspace = "../../.."
edition = "2018"
build = "build.rs"

[lib]
name = "gfx_backend_gl"

[features]
default = []
wgl = []

[dependencies]
arrayvec = "0.5"
bitflags = "1"
log = { version = "0.4" }
gfx-hal = { path = "../../hal", version = "0.4" }
auxil = { path = "../../auxil/auxil", version = "0.1", package = "gfx-auxil" }
smallvec = "0.6"
glow = "0.3.0-alpha3"
parking_lot = "0.10"
spirv_cross = { version = "0.16", features = ["glsl"] }
lazy_static = "1"
raw-window-handle = "0.3"
euclid = "0.20.7"
winit = "0.21.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = { version = "0.23.0", optional = true }
# TODO: Replace with actual version
surfman = { path = "../../../../surfman/surfman", features = ["sm-x11", "sm-raw-window-handle"], optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.6"
wasm-bindgen = "0.2.51"

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.6"
features = [
    "console",
    "Document",
    "Element",
    "HtmlCanvasElement",
    "HtmlElement",
    "Node",
    "Performance",
    "WebGlBuffer",
    "WebGlRenderingContext",
    "WebGl2RenderingContext",
    "WebGlProgram",
    "WebGlSampler",
    "WebGlShader",
    "WebGlTexture",
    "Window",
]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["libloaderapi", "windef", "wingdi", "winuser"] }

[build-dependencies]
gl_generator = "0.11"
